import Head from "next/head";
import dynamic from "next/dynamic";
import { useRouter } from "next/router";
import {
  AiFillLinkedin,
  AiFillGithub,
} from "react-icons/ai";
import { BsFillMoonStarsFill } from "react-icons/bs";
import { HiBars3, HiXMark } from "react-icons/hi2";
import { useEffect, useState } from "react";
const CanvasText = dynamic(() => import("../components/CanvasText"), { ssr: false });
const SkillBubbles = dynamic(() => import("../components/SkillBubbles"), { ssr: false });
import deved from "../public/valencia.jpg";
import code from "../public/code.png";
import design from "../public/fullstack.jpg";
import consulting from "../public/consulting.png";
import Image from "next/image";
import web1 from "../public/kanyesax.png";
import web2 from "../public/mriscans.png";
import web3 from "../public/segmentfetus.png";
import web4 from "../public/JPEG image 2.jpeg";
import web5 from "../public/braintumordetection.jpg";
import web6 from "../public/sam2.png";
import easypostLogo from "../public/0x0.png";
import sweetspotLogo from "../public/sweetspot-logo.svg";
import { FaXTwitter, FaEnvelope } from 'react-icons/fa6';

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);
  const [isMenuOpen, setIsMenuOpen] = useState(false);
  const [isDesktopMenuOpen, setIsDesktopMenuOpen] = useState(false);
  const router = useRouter();
  const resumeHref = `${router.basePath}/Pascal_Musabyimana_CV_EN_NL (1).pdf`;
  const navigationItems = [
    { label: "About", href: "#about" },
    { label: "Skills", href: "#skills" },
    { label: "Portfolio", href: "#portfolio" },
  ];

  useEffect(() => {
    document.body.style.overflow = isMenuOpen ? "hidden" : "";

    return () => {
      document.body.style.overflow = "";
    };
  }, [isMenuOpen]);

  const closeMenu = () => setIsMenuOpen(false);
  const closeDesktopMenu = () => setIsDesktopMenuOpen(false);

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>PascalMusabyimana</title>
        <meta name="description" content="Generated by Pascal Musabyimana" />
        <link rel="icon" href="/vexoimage.jpg" />
      </Head>
      <main className="bg-white px-4 dark:bg-gray-900 sm:px-6 md:px-12 lg:px-24 xl:px-32">
        <section className="min-h-screen">
          <nav className="sticky top-0 z-40 mb-8 flex items-center justify-between py-6 backdrop-blur dark:text-white">
            <h1 className="max-w-[14rem] text-sm leading-snug font-burtons sm:max-w-none sm:text-xl">
              developedbypascalmusabyimana
            </h1>

            <div className="relative hidden items-center gap-4 md:flex">
              <button
                type="button"
                onClick={() => setIsDesktopMenuOpen((open) => !open)}
                aria-label="Toggle navigation menu"
                aria-expanded={isDesktopMenuOpen}
                className="flex items-center gap-2 rounded-full border border-gray-200 px-4 py-2 text-sm font-medium text-gray-700 transition-colors hover:border-teal-500 hover:text-teal-600 dark:border-gray-700 dark:text-gray-200 dark:hover:text-teal-400"
              >
                <HiBars3 className="text-lg" />
                Menu
              </button>
              {isDesktopMenuOpen && (
                <div className="absolute right-[11rem] top-14 z-50 w-56 rounded-3xl border border-gray-200 bg-white p-3 shadow-2xl dark:border-gray-700 dark:bg-gray-900">
                  <div className="mb-2 flex items-center justify-between px-2 pt-1">
                    <p className="text-xs font-semibold uppercase tracking-[0.25em] text-teal-600 dark:text-teal-400">
                      Navigate
                    </p>
                    <button
                      type="button"
                      onClick={closeDesktopMenu}
                      aria-label="Close navigation menu"
                      className="rounded-full border border-gray-200 p-1 text-xl text-gray-900 dark:border-gray-700 dark:text-white"
                    >
                      <HiXMark />
                    </button>
                  </div>
                  <div className="flex flex-col gap-2">
                    {navigationItems.map((item) => (
                      <a
                        key={item.href}
                        href={item.href}
                        onClick={closeDesktopMenu}
                        className="rounded-2xl px-4 py-3 text-sm font-medium text-gray-700 transition-colors hover:bg-teal-50 hover:text-teal-600 dark:text-gray-200 dark:hover:bg-gray-800 dark:hover:text-teal-400"
                      >
                        {item.label}
                      </a>
                    ))}
                  </div>
                </div>
              )}
              <button
                type="button"
                onClick={() => setDarkMode(!darkMode)}
                aria-label="Toggle dark mode"
                className="cursor-pointer text-2xl text-gray-700 transition-colors hover:text-teal-600 dark:text-gray-200 dark:hover:text-teal-400"
              >
                <BsFillMoonStarsFill />
              </button>
              <a
                className="rounded-full bg-gradient-to-r from-cyan-500 to-teal-500 px-5 py-2 text-white shadow-lg shadow-teal-500/20 transition-transform hover:-translate-y-0.5"
                href={resumeHref}
                target="_blank"
                rel="noopener noreferrer"
              >
                Resume
              </a>
            </div>

            <div className="flex items-center gap-3 md:hidden">
              <button
                type="button"
                onClick={() => setDarkMode(!darkMode)}
                aria-label="Toggle dark mode"
                className="rounded-full border border-gray-200 p-2 text-xl text-gray-700 dark:border-gray-700 dark:text-gray-200"
              >
                <BsFillMoonStarsFill />
              </button>
              <button
                type="button"
                onClick={() => setIsMenuOpen(true)}
                aria-label="Open menu"
                aria-expanded={isMenuOpen}
                className="rounded-full border border-gray-200 p-2 text-2xl text-gray-900 dark:border-gray-700 dark:text-white"
              >
                <HiBars3 />
              </button>
            </div>
          </nav>

          {isMenuOpen && (
            <div className="fixed inset-0 z-50 md:hidden">
              <button
                type="button"
                aria-label="Close menu overlay"
                onClick={closeMenu}
                className="absolute inset-0 bg-gray-950/50 backdrop-blur-sm"
              />
              <div className="absolute right-4 top-4 w-[min(20rem,calc(100vw-2rem))] rounded-3xl bg-white p-5 shadow-2xl dark:bg-gray-900">
                <div className="mb-6 flex items-center justify-between">
                  <p className="text-sm font-semibold uppercase tracking-[0.25em] text-teal-600 dark:text-teal-400">
                    Menu
                  </p>
                  <button
                    type="button"
                    onClick={closeMenu}
                    aria-label="Close menu"
                    className="rounded-full border border-gray-200 p-2 text-2xl text-gray-900 dark:border-gray-700 dark:text-white"
                  >
                    <HiXMark />
                  </button>
                </div>

                <div className="flex flex-col gap-3">
                  {navigationItems.map((item) => (
                    <a
                      key={item.href}
                      href={item.href}
                      onClick={closeMenu}
                      className="rounded-2xl border border-gray-200 px-4 py-3 text-base font-medium text-gray-900 transition-colors hover:border-teal-500 hover:text-teal-600 dark:border-gray-700 dark:text-white dark:hover:text-teal-400"
                    >
                      {item.label}
                    </a>
                  ))}
                  <a
                    className="rounded-2xl bg-gradient-to-r from-cyan-500 to-teal-500 px-4 py-3 text-center text-base font-semibold text-white"
                    href={resumeHref}
                    target="_blank"
                    rel="noopener noreferrer"
                    onClick={closeMenu}
                  >
                    Open Resume
                  </a>
                </div>
              </div>
            </div>
          )}

          <div className="px-0 py-6 text-center sm:px-4 sm:py-10">
            <h2 className="py-2 text-4xl font-medium text-teal-600 dark:text-teal-400 sm:text-5xl md:text-6xl">
              Pascal Musabyimana
            </h2>
            <h3 className="px-2 py-2 text-xl dark:text-white sm:text-2xl md:text-3xl">
              Computer Vision Enthousiast.
            </h3>
            <div className="mx-auto max-w-xl py-5">
              <CanvasText
                text="I am a Computer Vision Enthousiast. I use Ultralytics, Label Studio, Docker, React, OpenCV, YOLOv8, Pytorch, Tensorflow, Huggingface, Kaggle and Python."
                fontFamily="Poppins, sans-serif"
                fontSize={18}
                lineHeight={32}
                color={darkMode ? '#e5e7eb' : '#1f2937'}
              />
            </div>
            <div className="mx-auto grid max-w-md grid-cols-3 place-items-center gap-4 py-6 text-4xl text-gray-600 dark:text-gray-400 sm:flex sm:max-w-none sm:justify-center sm:gap-10 sm:text-5xl">
              <a href="https://x.com/pascalmusa51964?s=11" aria-label="X profile" className="transition-transform duration-200 hover:scale-110"><FaXTwitter /></a>
              <a href="https://be.linkedin.com/in/pascal-musabyimana-573b66178" aria-label="LinkedIn profile" className="transition-transform duration-200 hover:scale-110"><AiFillLinkedin /></a>
              <a href="https://github.com/pascal-maker" aria-label="GitHub profile" className="transition-transform duration-200 hover:scale-110"><AiFillGithub /></a>
              <a href="mailto:pascal-musa@hotmail.com" aria-label="Email Pascal" className="transition-transform duration-200 hover:scale-110"><FaEnvelope /></a>
              <a href="https://huggingface.co/pascal-maker" target="_blank" rel="noopener noreferrer" className="text-3xl transition-transform duration-200 hover:scale-110 sm:text-4xl" title="Hugging Face Profile">🤗</a>
            </div>

            <div className="relative mx-auto mt-12 h-[22rem] w-full max-w-[18rem] overflow-hidden rounded-[2rem] bg-gradient-to-b from-teal-500 shadow-xl shadow-teal-500/20 sm:h-[26rem] sm:max-w-[20rem] md:mt-16 md:h-[32rem] md:max-w-[24rem]">
              <Image
                src={deved}
                layout="fill"
                objectFit="contain"
                alt=""
                sizes="(max-width: 768px) 80px, (max-width: 1024px) 96px, 192px"
              />
            </div>

            <h3 id="about" className="py-1 text-3xl dark:text-white">About Me</h3>
            <div className="py-2">
              <CanvasText
                text="I'm a student at Howest University of Applied Sciences. In my free time, I like to build websites and apps. Let me help you fulfill your dream as an entrepreneur. If you need a landing page, a working proof of concept of a computer-vision project, or a brand new website for your marketing agency, I'm your guy. Let's work together to fulfill your potential to the fullest."
                fontFamily="Poppins, sans-serif"
                fontSize={16}
                lineHeight={32}
                color={darkMode ? '#e5e7eb' : '#1f2937'}
              />
            </div>
            <div className="py-2">
              <CanvasText
                text="I have worked with an experienced developer who worked at Meta. I have also worked for companies such as Easypost and Sweetspot. When it comes to user experience or design, I always try to enhance the user experience based on your target audience."
                fontFamily="Poppins, sans-serif"
                fontSize={16}
                lineHeight={32}
                color={darkMode ? '#e5e7eb' : '#1f2937'}
              />
            </div>
            <h3 className="py-4 text-3xl dark:text-white">Companies I Worked For</h3>
            <div className="flex flex-col items-center justify-center gap-8 rounded-2xl border border-gray-300 p-6 sm:flex-row">
              <div className="flex flex-col items-center gap-2">
                <a
                  href="https://www.linkedin.com/posts/pascal-musabyimana-573b66178_hey-linkedin-network-long-time-ago-activity-7345483853223931904-btig?utm_source=share&utm_medium=member_desktop&rcm=ACoAACoslacB56MwdRN6bL1P1uM5qLdxwYzUcg8"
                  target="_blank"
                  rel="noopener noreferrer"
                  className="hover:opacity-80 transition-opacity duration-200"
                >
                  <Image
                    src={easypostLogo}
                    width={100}
                    height={100}
                    alt="Easypost Company"
                    className="rounded-lg cursor-pointer border border-gray-400"
                  />
                </a>
                <p className="text-sm text-gray-500">Easypost</p>
              </div>
              <div className="flex flex-col items-center gap-2">
                <Image
                  src={sweetspotLogo}
                  width={100}
                  height={100}
                  alt="Sweetspot Company"
                  className="rounded-lg border border-gray-400"
                />
                <p className="text-sm text-gray-500">Sweetspot</p>
              </div>
            </div>
          </div>

          {/* Skills Section */}
          <section id="skills" className="scroll-mt-28 py-6">
            <div className="mb-6 text-center">
              <h3 className="py-1 text-3xl dark:text-white">Skills</h3>
              <p className="mx-auto max-w-2xl py-2 text-md leading-8 text-gray-800 dark:text-gray-200">
                Everything I use across product work, engineering, and consulting.
              </p>
            </div>

            <div className="grid grid-cols-1 gap-8 md:grid-cols-2 xl:grid-cols-3">
              <div className="my-4 flex h-full flex-col rounded-xl p-10 text-center shadow-lg dark:bg-white">
              <Image src={design} width={100} height={100} alt="" />
              <h3 className="text-lg font-medium pt-8 pb-2">Coding Languages</h3>
              <p className="py-2">Coding Languages I have used to build my projects.</p>
              <h4 className="py-4 text-teal-600">Languages I Use</h4>
              <SkillBubbles
                skills={['JavaScript', 'Objective-C', 'Swift', 'Node.js', 'Python', 'C#']}
                fontFamily="Poppins, sans-serif"
                fontSize={13}
                textColor="#0f766e"
                bgColor="#ccfbf1"
              />
              </div>
              <div className="my-4 flex h-full flex-col rounded-xl p-10 text-center shadow-lg dark:bg-white">
                <Image src={code} width={100} height={100} alt="" />
                <h3 className="text-lg font-medium pt-8 pb-2">Frameworks</h3>
                <p className="py-2">Do you have an idea for your next great startup? Let&apos;s make it a reality.</p>
                <h4 className="py-4 text-teal-600">Tools & Technologies I Use/Have Used</h4>
                <p className="text-gray-800 py-1">React</p>
                <p className="text-gray-800 py-1">Node.js</p>
                <p className="text-gray-800 py-1">React-Native</p>
                <p className="text-gray-800 py-1">Next.js</p>
                <p className="text-gray-800 py-1">Langflow</p>
                <p className="text-gray-800 py-1">Pytorch</p>
                <p className="text-gray-800 py-1">Ultralytics</p>
                <p className="text-gray-800 py-1">TensorFlow</p>
                <p className="text-gray-800 py-1">Huggingface</p>
                <p className="text-gray-800 py-1">Agentarium</p>
                <p className="text-gray-800 py-1">Pydantic</p>
                <p className="text-gray-800 py-1">MCP</p>
                <p className="text-gray-800 py-1">Docker</p>
                <p className="text-gray-800 py-1">Langfuse</p>
                <p className="text-gray-800 py-1">Roboflow</p>
                <p className="text-gray-800 py-1">OpenCV</p>
                <p className="text-gray-800 py-1">Swarm</p>
              </div>
              <div className="my-4 flex h-full flex-col rounded-xl p-10 text-center shadow-lg dark:bg-white">
                <Image src={consulting} width={100} height={100} alt="" />
                <h3 className="text-lg font-medium pt-8 pb-2">Consulting</h3>
                <p className="py-2">I&apos;m here to help you with your software development needs.</p>
                <h4 className="py-4 text-teal-600">Let&apos;s Talk</h4>
                <SkillBubbles
                  skills={['Freelance', 'Landing Pages', 'Computer Vision', 'Proof of Concept']}
                  fontFamily="Poppins, sans-serif"
                  fontSize={13}
                  textColor="#0f766e"
                  bgColor="#ccfbf1"
                />
              </div>
            </div>
          </section>

          {/* Portfolio Section */}
          <h3 id="portfolio" className="py-1 text-3xl dark:text-white">My Portfolio</h3>
          <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
            Some of the projects I&apos;ve worked on.
          </p>
          <div className="grid grid-cols-1 gap-6 pb-12 sm:grid-cols-2 xl:grid-cols-3">
            <a
              href="https://www.linkedin.com/in/pascal-musabyimana-573b66178/overlay/1727034581247/single-media-viewer/?profileId=ACoAACoslacB56MwdRN6bL1P1uM5qLdxwYzUcg8"
              className="overflow-hidden rounded-2xl shadow-md transition-transform duration-300 hover:-translate-y-1"
            >
              <Image
                src={web1}
                className="rounded-2xl object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                alt=""
              />
            </a>
            <a href="" className="overflow-hidden rounded-2xl shadow-md transition-transform duration-300 hover:-translate-y-1">
              <Image
                src={web2}
                className="rounded-2xl object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                alt=""
              />
            </a>
            <a href="https://www.linkedin.com/posts/pascal-musabyimana-573b66178_meta-computervision-segmentation-activity-7169017148386840576-4GCh?utm_source=share&utm_medium=member_desktop" className="overflow-hidden rounded-2xl shadow-md transition-transform duration-300 hover:-translate-y-1">
              <Image
                src={web3}
                className="rounded-2xl object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                alt=""
              />
            </a>
            <a
              href="https://www.linkedin.com/posts/pascal-musabyimana-573b66178_hey-linkedin-network-i-have-decided-activity-7153396537753030657-_Vzm?utm_source=share&utm_medium=member_desktop"
              className="overflow-hidden rounded-2xl shadow-md transition-transform duration-300 hover:-translate-y-1"
            >
              <Image
                src={web4}
                className="rounded-2xl object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                alt=""
              />
            </a>
            <a
              href="https://medium.com/@pascalmusa/brain-tumor-detection-yolov8-vs-sam-2-7a19ad44efb4"
              className="overflow-hidden rounded-2xl shadow-md transition-transform duration-300 hover:-translate-y-1"
            >
              <Image
                src={web5}
                className="rounded-2xl object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                alt=""
              />
            </a>
            <a
              href="https://medium.com/@pascalmusa/brain-tumor-detection-yolov8-vs-sam-2-7a19ad44efb4"
              className="overflow-hidden rounded-2xl shadow-md transition-transform duration-300 hover:-translate-y-1"
            >
              <Image
                src={web6}
                className="rounded-2xl object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                alt=""
              />
            </a>
          </div>


        </section>
      </main>
    </div>
  );
}
