import Head from "next/head";
import dynamic from "next/dynamic";
import { useRouter } from "next/router";
import {
  AiFillLinkedin,
  AiFillGithub,
} from "react-icons/ai";
import { BsFillMoonStarsFill } from "react-icons/bs";
import { useState } from "react";
const CanvasText = dynamic(() => import("../components/CanvasText"), { ssr: false });
const SkillBubbles = dynamic(() => import("../components/SkillBubbles"), { ssr: false });
import deved from "../public/valencia.jpg";
import code from "../public/code.png";
import design from "../public/fullstack.jpg";
import consulting from "../public/consulting.png";
import Image from "next/image";
import web1 from "../public/kanyesax.png";
import web2 from "../public/mriscans.png";
import web3 from "../public/segmentfetus.png";
import web4 from "../public/footage.png";
import web5 from "../public/braintumordetection.jpg";
import web6 from "../public/sam2.png";
import easypostLogo from "../public/0x0.png";
import { FaXTwitter, FaEnvelope } from 'react-icons/fa6';

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);
  const router = useRouter();
  const resumeHref = `${router.basePath}/resumeupdated.pdf`;

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>PascalMusabyimana</title>
        <meta name="description" content="Generated by Pascal Musabyimana" />
        <link rel="icon" href="/vexoimage.jpg" />
      </Head>
      <main className="bg-white px-6 dark:bg-gray-900 md:px-20 lg:px-40">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between dark:text-white">
            <h1 className="font-burtons text-xl">developedbypascalmusabyimana</h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill
                  onClick={() => setDarkMode(!darkMode)}
                  className="cursor-pointer text-2xl"
                />
              </li>
              <li>
                <a
                  className="bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 border-none rounded-md ml-8"
                  href={resumeHref}
                  target="_blank"
                  rel="noopener noreferrer"
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>
          <div className="text-center p-10 py-10">
            <h2 className="text-4xl py-2 text-teal-600 font-medium dark:text-teal-400 md:text-6xl">
              Pascal Musabyimana
            </h2>
            <h3 className="text-2xl py-2 dark:text-white md:text-3xl">
              Computer Vision Enthousiast.
            </h3>
            <div className="py-5 max-w-xl mx-auto">
              <CanvasText
                text="I am a Computer Vision Enthousiast. I use Ultralytics, Label Studio, Docker, React, OpenCV, YOLOv8, Pytorch, Tensorflow, Huggingface, Kaggle and Python."
                fontFamily="Poppins, sans-serif"
                fontSize={18}
                lineHeight={32}
                color={darkMode ? '#e5e7eb' : '#1f2937'}
              />
            </div>
            <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-gray-400">
              <a href="https://x.com/pascalmusa51964?s=11"><FaXTwitter /></a>
              <a href="https://be.linkedin.com/in/pascal-musabyimana-573b66178"><AiFillLinkedin /></a>
              <a href="https://github.com/pascal-maker"><AiFillGithub /></a>
              <a href="https://pascal-musa@hotmail.com"><FaEnvelope /></a>
              <a href="https://huggingface.co/pascal-maker" target="_blank" rel="noopener noreferrer" className="hover:scale-110 transition-transform duration-200 text-4xl" title="Hugging Face Profile">🤗</a>
            </div>

            <div className="mx-auto bg-gradient-to-b from-teal-500 rounded-2xl w-72 h-96 relative overflow-hidden mt-20 md:h-[32rem] md:w-[24rem]">
              <Image
                src={deved}
                layout="fill"
                objectFit="contain"
                alt=""
                sizes="(max-width: 768px) 80px, (max-width: 1024px) 96px, 192px"
              />
            </div>

            <h3 className="text-3xl py-1 dark:text-white">About Me</h3>
            <div className="py-2">
              <CanvasText
                text="I'm a student at Howest University of Applied Sciences. In my free time, I like to build websites and apps. Let me help you fulfill your dream as an entrepreneur. If you need a landing page, a working proof of concept of a computer-vision project, or a brand new website for your marketing agency, I'm your guy. Let's work together to fulfill your potential to the fullest."
                fontFamily="Poppins, sans-serif"
                fontSize={16}
                lineHeight={32}
                color={darkMode ? '#e5e7eb' : '#1f2937'}
              />
            </div>
            <div className="py-2">
              <CanvasText
                text="I have worked with an experienced developer who worked at Meta. I have also collaborated with companies such as Easypost. When it comes to user experience or design, I always try to enhance the user experience based on your target audience."
                fontFamily="Poppins, sans-serif"
                fontSize={16}
                lineHeight={32}
                color={darkMode ? '#e5e7eb' : '#1f2937'}
              />
            </div>
            <div className="flex justify-center items-center py-4 border-2 border-gray-300 rounded-lg p-4">
              <a
                href="https://www.linkedin.com/posts/pascal-musabyimana-573b66178_hey-linkedin-network-long-time-ago-activity-7345483853223931904-btig?utm_source=share&utm_medium=member_desktop&rcm=ACoAACoslacB56MwdRN6bL1P1uM5qLdxwYzUcg8"
                target="_blank"
                rel="noopener noreferrer"
                className="hover:opacity-80 transition-opacity duration-200"
              >
                <Image
                  src={easypostLogo}
                  width={100}
                  height={100}
                  alt="Easypost Company"
                  className="rounded-lg cursor-pointer border border-gray-400"
                />
              </a>
              <p className="text-sm text-gray-500 ml-4">Easypost Logo</p>
            </div>
          </div>

          {/* Skills Section */}
          <div className="lg:flex gap-10">
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1">
              <Image src={design} width={100} height={100} alt="" />
              <h3 className="text-lg font-medium pt-8 pb-2">Coding Languages</h3>
              <p className="py-2">Coding Languages I have used to build my projects.</p>
              <h4 className="py-4 text-teal-600">Languages I Use</h4>
              <SkillBubbles
                skills={['JavaScript', 'Objective-C', 'Swift', 'Node.js', 'Python', 'C#']}
                fontFamily="Poppins, sans-serif"
                fontSize={13}
                textColor="#0f766e"
                bgColor="#ccfbf1"
              />
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1">
              <Image src={code} width={100} height={100} alt="" />
              <h3 className="text-lg font-medium pt-8 pb-2">Frameworks</h3>
              <p className="py-2">Do you have an idea for your next great startup? Let&apos;s make it a reality.</p>
              <h4 className="py-4 text-teal-600">Tools & Technologies I Use/Have Used</h4>
              <SkillBubbles
                skills={['React', 'Node.js', 'React-Native', 'Next.js', 'Langflow', 'Pytorch', 'Ultralytics', 'TensorFlow', 'Huggingface', 'Agentarium', 'Pydantic', 'Swarm']}
                fontFamily="Poppins, sans-serif"
                fontSize={13}
                textColor="#0f766e"
                bgColor="#ccfbf1"
              />
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1">
              <Image src={consulting} width={100} height={100} alt="" />
              <h3 className="text-lg font-medium pt-8 pb-2">Consulting</h3>
              <p className="py-2">I&apos;m here to help you with your software development needs.</p>
              <h4 className="py-4 text-teal-600">Let&apos;s Talk</h4>
              <SkillBubbles
                skills={['Freelance', 'Landing Pages', 'Computer Vision', 'Proof of Concept']}
                fontFamily="Poppins, sans-serif"
                fontSize={13}
                textColor="#0f766e"
                bgColor="#ccfbf1"
              />
            </div>
          </div>

          {/* Portfolio Section */}
          <h3 className="text-3xl py-1 dark:text-white">My Portfolio</h3>
          <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
            Some of the projects I&apos;ve worked on.
          </p>
          <div className="flex flex-col gap-10 lg:flex-row lg:flex-wrap">
            <a
              href="https://www.linkedin.com/in/pascal-musabyimana-573b66178/overlay/1727034581247/single-media-viewer/?profileId=ACoAACoslacB56MwdRN6bL1P1uM5qLdxwYzUcg8"
              className="basis-1/3 flex-1"
            >
              <Image
                src={web1}
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                alt=""
              />
            </a>
            <a href="" className="basis-1/3 flex-1">
              <Image
                src={web2}
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                alt=""
              />
            </a>
            <a href="https://www.linkedin.com/posts/pascal-musabyimana-573b66178_meta-computervision-segmentation-activity-7169017148386840576-4GCh?utm_source=share&utm_medium=member_desktop" className="basis-1/3 flex-1">
              <Image
                src={web3}
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                alt=""
              />
            </a>
            <a
              href="https://www.linkedin.com/posts/pascal-musabyimana-573b66178_hey-linkedin-network-i-have-decided-activity-7153396537753030657-_Vzm?utm_source=share&utm_medium=member_desktop"
              className="basis-1/3 flex-1"
            >
              <Image
                src={web4}
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                alt=""
              />
            </a>
            <a
              href="https://medium.com/@pascalmusa/brain-tumor-detection-yolov8-vs-sam-2-7a19ad44efb4"
              className="basis-1/3 flex-1"
            >
              <Image
                src={web5}
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                alt=""
              />
            </a>
            <a
              href="https://medium.com/@pascalmusa/brain-tumor-detection-yolov8-vs-sam-2-7a19ad44efb4"
              className="basis-1/3 flex-1"
            >
              <Image
                src={web6}
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                alt=""
              />
            </a>
          </div>


        </section>
      </main>
    </div>
  );
}
